api_version = "2025-07"

[[extensions]]
handle = "donation-cart-transform"
name = "t:name"
description = "t:description"
uid = "64bcb866-f231-ddca-dccd-155ecbd9f43301838f31"
type = "function"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
